--- 
entities: 
  supermaster: 
    actions: 
      add: 
        id: false
      edit: 
        id: true
      grid: 
        default: true
        id: false
      remove: 
        id: true
    namespace: OUTRAGEdns.Supermaster
    table: supermasters
    type: supermaster
